#' Grob aesthetic list used to give the grobs their aesthetics.
#'
#' @return A list with all possible aesthetic elements that can be adjusted, with the class of "grob_aes_list".
#' @export

ga_list <- function(background_color = NULL,
                    background_alpha = NULL,
                    borders = NULL,
                    border_color = NULL,
                    border_width = NULL,
                    font_face = NULL,
                    text_color = NULL,
                    text_align = NULL,
                    text_v_align = NULL,
                    text_just = NULL,
                    text_v_just = NULL,
                    text_cex = NULL,
                    text_font = NULL,
                    round_rect_radius = NULL,
                    group_elements = NULL,
                    row_heights = NULL,
                    column_widths = NULL,
                    cell_sep = NULL,
                    colname_font_face = NULL,
                    colname_background_color = NULL,
                    colname_background_alpha = NULL,
                    colname_borders = NULL,
                    colname_border_color = NULL,
                    colname_border_width = NULL,
                    colname_text_color = NULL,
                    colname_text_align = NULL,
                    colname_text_v_align = NULL,
                    colname_text_just = NULL,
                    colname_text_v_just = NULL,
                    colname_text_cex = NULL,
                    colname_text_font = NULL,
                    colname_round_rect_radius = NULL,
                    colname_group_elements = NULL,
                    colname_row_heights = NULL,
                    colname_column_widths = NULL,
                    colname_cell_sep = NULL,
                    color_gradient_columns = NULL,
                    color_gradient_binary = NULL,
                    color_binary_cut_off = NULL,
                    color_binary_high = NULL,
                    color_binary_low = NULL,
                    color_binary_equal = NULL,
                    color_gradient_max = NULL,
                    color_gradient_mid = NULL,
                    color_gradient_min = NULL,
                    maintain_aspect_ratio = NULL,
                    hjust = NULL,
                    vjust = NULL,
                    n_lines = NULL,
                    sep = NULL){

  grob_aes_list <- list(
    font_face = font_face,
    background_color = background_color,
    background_alpha = background_alpha,
    borders = borders,
    border_color = border_color,
    border_width = border_width,
    text_color = text_color,
    text_align = text_align,
    text_v_align = text_v_align,
    text_just = text_just,
    text_v_just = text_v_just,
    text_cex = text_cex,
    text_font = text_font,
    round_rect_radius = round_rect_radius,
    group_elements = group_elements,
    row_heights = row_heights,
    column_widths = column_widths,
    cell_sep = cell_sep,
    colname_font_face = colname_font_face,
    colname_background_color = colname_background_color,
    colname_background_alpha = colname_background_alpha,
    colname_borders = colname_borders,
    colname_border_color = colname_border_color,
    colname_border_width = colname_border_width,
    colname_text_color = colname_text_color,
    colname_text_align = colname_text_align,
    colname_text_v_align = colname_text_v_align,
    colname_text_just = colname_text_just,
    colname_text_v_just = colname_text_v_just,
    colname_text_cex = colname_text_cex,
    colname_text_font = colname_text_font,
    colname_round_rect_radius = colname_round_rect_radius,
    colname_group_elements = colname_group_elements,
    colname_row_heights = colname_row_heights,
    colname_column_widths = colname_column_widths,
    colname_cell_sep = colname_cell_sep,
    color_gradient_columns = color_gradient_columns,
    color_gradient_binary = color_gradient_binary,
    color_binary_cut_off = color_binary_cut_off,
    color_binary_high = color_binary_high,
    color_binary_low = color_binary_low,
    color_binary_equal = color_binary_equal,
    color_gradient_max = color_gradient_max,
    color_gradient_mid = color_gradient_mid,
    color_gradient_min = color_gradient_min,
    maintain_aspect_ratio = maintain_aspect_ratio,
    hjust = hjust,
    vjust = vjust,
    n_lines = n_lines,
    sep = sep)

  grob_aes_list <- lapply(grob_aes_list, convert_to_matrix)
  class(grob_aes_list) <- 'grob_aes_list'
  grob_aes_list

}


